### ISSUE TITLE
Invalid isoformat string

### ISSUE THREAD

**Issue by elouan-lb** [gerlos/bbbattendance#6]
Hello, I'm getting this error when trying to run the script:

```
Traceback (most recent call last):
  File "./bbbattendance.py", line 261, in <module>
    parsed_attendance = parse_data(raw_attendance)
  File "./bbbattendance.py", line 165, in parse_data
    timestamp = dt.datetime.fromisoformat(raw_timestamp)
ValueError: Invalid isoformat string: '2021-06-26T09:20:09.316Z INFO'
```

Do you have any idea what the problem could be? Thank you for your work!

**Comment by gerlos** [comment]
Thanks, this seems related to https://github.com/gerlos/bbbattendance/issues/1#issue-828097644

I'll give it a look.

**Comment by donbowman** [comment]
```
index 58cc146..b8c39e8 100755
--- a/bbbattendance.py
+++ b/bbbattendance.py
@@ -156,7 +156,7 @@ def parse_data(raw_attendance):
     parsed_attendance = []
     for line in raw_attendance:
         # extract timestamps
-        raw_timestamp = line[0:29]
+        raw_timestamp = line[0:29].split(' ')[0]
         try:
             # datetime.datetime.fromisoformat doesn't expect a Z in time zone
             # so we replace it with the explicit time zone "+00:00"

```
